---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-databases-k8s-k-io-v1-mysqldatabase
  failurePolicy: Fail
  name: mmysqldatabase.kb.io
  rules:
  - apiGroups:
    - databases.k8s.k.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mysqldatabases
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-databases-k8s-k-io-v1-mysqldatabase
  failurePolicy: Fail
  name: vmysqldatabase.kb.io
  rules:
  - apiGroups:
    - databases.k8s.k.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mysqldatabases
  sideEffects: None
