# permissions for end users to edit mysqlservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysqlserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: database-provisioner
    app.kubernetes.io/part-of: database-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: mysqlserver-editor-role
rules:
- apiGroups:
  - databases.k8s.k.io
  resources:
  - mysqlservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.k8s.k.io
  resources:
  - mysqlservers/status
  verbs:
  - get
