name: Build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: registry.k.io
          username: ${{ secrets.KRYSTAL_REGISTRY_USERNAME }}
          password: ${{ secrets.KRYSTAL_REGISTRY_PASSWORD }}
      - run: |
          make save-manifests docker-build docker-push IMG=registry.k.io/kubernetes/database-provisioner:${{ github.ref_name }}
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            manifest.yaml
