name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: tag
        run: |
          TAG="${GITHUB_REF#refs/heads/}"
          if [ -z "$TAG" ]; then exit 1; fi
          if [[ $TAG == "main" ]]; then TAG="latest"; else TAG="branch-${TAG}"; fi
          echo "::set-output name=tag::${TAG}"
      - run: |
          make docker-build docker-push IMG=ghcr.io/krystal/database-provisioner:${{ steps.tag.outputs.tag }}
